### ISSUE TITLE
如何设置默认选中状态？添加全选

### ISSUE THREAD

**Issue by howmeirong** [akshathjain/grouped_buttons#1]
我想添加全选功能，如何手动设置选中呢

**Comment by akshathjain** [comment]
@howmeirong Can you please translate this issue to English?

**Comment by akshathjain** [comment]
@howmeirong I've translated your question to English, and here's what I've got:
- How do I set the default selection state? Add all selection. 
- I want to add a full selection function, how to manually set the selection?

\
To answer your question:

**Setting Defaults / Manually Editing `CheckboxGroup`**
Simply use the `checked` property to specify which Checkboxes should be checked by default and to manually set the selection. For example: 
```
List<String> _defaultChecked = ["Monday, Wednesday"];

CheckboxGroup(
  labels: <String>[
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
  ],
  checked: _defaultChecked,
  onSelected: (List<String> checked) => setState((){
    _defaultChecked = checked;
  });
);
```
In this example, you end up with with 7 Checkboxes, with the Monday and Wednesday Checkboxes being checked by default. The important thing to note here is that if you decide to manually specify which ones are checked, you need to provide a function to the `onSelected` property that updates `_defaultChecked ` by calling `setState()` every time the user makes a new selection (otherwise, the `CheckboxGroup` state won't change).

If you want to manually change what is checked, you can just change `_defaultChecked` inside of a `setState()` to what you want checked. For example:
```
setState((){
  _defaultChecked = ["Thursday", "Friday"];
});
```
This will override the user selection and make only Thursday and Friday checked.

\
**Setting Defaults / Manually Editing `RadioButtonGroup`**
Simply use the `picked` property to specify which RadioButton should be selected by default and to manually set the selection. For example: 
```
String _defaultPicked  = "C";

RadioButtonGroup(
  labels: <String>[
    "A",
    "B",
    "C",
    "D",
    "E",
  ]
  picked: _defaultPicked,
  onSelected: (String selected) => setState((){
    _defaultPicked = selected;
  }),
);
```
In this example, you end up with with 5 RadioButtons, with the C RadioButton being picked / selected by default. The important thing to note here is that if you decide to manually specify which ones are selected, you need to provide a function to the `onSelected` property that updates `_defaultPicked` by calling `setState()` every time the user makes a new selection (otherwise, the `RadioButtonGroup` state won't change).

If you want to manually change what is selected, you can just change `_defaultPicked` inside of a `setState()` to what you want checked. For example:
```
setState((){
  _defaultPicked = "A";
});
```
This will override the user selection and make only A selected.

\
\
I've gone ahead and closed this issue for now, but if you have any further questions, please feel free to reopen / comment on this.
